### ISSUE TITLE
Release most recent changes

### ISSUE THREAD

**Issue by raducal** [naver/mesh-simplifier#3]
Hi @WoodNeck,

The most recent changes you made here were never released. Could you please consider creating a new release that includes these updates? The current latest release (v1.0.0) does not support newer versions of Three.JS.

Thanks

**Comment by WoodNeck** [comment]
Hello @raducostica.
I think I postponed the release hoping for adding some new updates for this package.
So, there's actually a release supporting newer versions of three.js (above 0.134) exists with the tag `@next`.

You can install that version with that tag, but I'll also release that version as latest right now.
I choose the version as `2.0.0-beta.0` back then since it was a breaking change(with no backward compatibility),
But I'll release it as `1.0.1` regarding semver policy: https://github.com/semver/semver/issues/148

**Comment by WoodNeck** [comment]
Released v1.0.1
